name: 'My Notification Action'
description: 'Send notifications on success or failure'
author: 'AdrianEunoia'
branding:
  icon: 'bell'
  color: 'blue'
inputs:
  webhook-teams:
    description: 'Teams Webhook URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send a notification on success
      id: notifySuccess
      run: ./src/success-script.sh
    - name: Send a notification on failure
      id: notifyFailure
      run: ./src/failure-script.sh