name: 'My Notification Action'
description: 'Send notifications on success or failure'
author: 'AdrianEunoia'
branding:
  icon: 'bell'
  color: 'blue'
inputs:
  webhook-teams:
    description: 'Teams Webhook URL'
    required: true
runs:
  using: 'docker'
  image: 'eunoiadocker/msteams-notifications-webhook:v1.11'
  args:
    - ${{ inputs.webhook-teams }}