name: WorkflowStatus

on:
  push:
    branches:
      - main

jobs:
  randomWorkflowJob:
    name: Trabajo de ejemplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2
          
  notificationActions:
    name: Enviar Notificación
    runs-on: ubuntu-latest
    needs:
      - randomWorkflowJob

    steps:
      - name: Ejecutar Tu Acción
        uses: AdrianEunoia/msteams-notifications-webhook@v1.0
        with:
          webhook-teams: ${{ secrets.WEBHOOK_TEAMS }}
          